name: .NET Core Desktop CI

permissions:
  contents: read

on:
  push:
    branches: [ "ReuelAlbert-Dev-patch-1" ]
  pull_request:
    branches: [ "ReuelAlbert-Dev-patch-1" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      SOLUTION_NAME: MyApp.sln          # Set your solution file, e.g. MyWpfApp.sln
      TEST_PROJECT_PATH: tests\MyApp.Tests\MyApp.Tests.csproj # Update with your test project's path
      WAP_PROJECT_DIR: src\MyApp.Package    # Update with your Windows Application Packaging project directory
      WAP_PROJECT_PATH: src\MyApp.Package\MyApp.Package.wapproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION_NAME

    - name: Build Solution
      run: dotnet build $env:SOLUTION_NAME --configuration ${{ matrix.configuration }} --no-restore

    - name: Run Unit Tests
      run: dotnet test $env:TEST_PROJECT_PATH --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Restore WAP project (for packaging)
      run: msbuild $env:WAP_PROJECT_PATH /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Decode PFX certificate from secret
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      run: |
        $pfxBytes = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $outPath = Join-Path -Path $env:WAP_PROJECT_DIR -ChildPath "GitHubActionsWorkflow.pfx"
        [IO.File]::WriteAllBytes($outPath, $pfxBytes)

    - name: Package application
      run: msbuild $env:WAP_PROJECT_PATH /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64" /p:PackageCertificateKeyFile="GitHubActionsWorkflow.pfx" /p:PackageCertificatePassword="${{ secrets.Pfx_Key }}"

    - name: Clean up certificate
      run: |
        Remove-Item "$env:WAP_PROJECT_DIR\GitHubActionsWorkflow.pfx" -Force
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}

    - name: Upload MSIX Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package (${% raw %}{{ matrix.configuration }}{% endraw %})
        path: ${{ env.WAP_PROJECT_DIR }}\AppPackages
