# Problem in this file has been resolved

name: .NET Core Desktop CI

permissions:
  contents: read

on:
  push:
    branches: [ "ReuelAlbert-Dev-patch-1" ]
  pull_request:
    branches: [ "ReuelAlbert-Dev-patch-1" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      SOLUTION_NAME: MyApp.sln          # Set your solution file, e.g. MyWpfApp.sln
      TEST_PROJECT_PATH: tests\MyApp.Tests\MyApp.Tests.csproj # Update with your test project's path
      WAP_PROJECT_DIR: src\MyApp.Package    # Update with your Windows Application Packaging project directory
      WAP_PROJECT_PATH: src\MyApp.Package\MyApp.Package.wapproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore $env:SOLUTION_NAME

    - name: Build Solution
      run: dotnet build $env:SOLUTION_NAME --configuration ${{ matrix.configuration }} --no-restore

    - name: Run Unit Tests
      run: dotnet test $env:TEST_PROJECT_PATH --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Restore WAP project (for packaging)
      run: msbuild $env:WAP_PROJECT_PATH /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Decode PFX certificate from secret
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:WAP_PROJECT_DIR -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild $env:WAP_PROJECT_PATH /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:WAP_PROJECT_DIR\GitHubActionsWorkflow.pfx

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: MSIX Package (${{ matrix.configuration }})
        path: ${{ env.WAP_PROJECT_DIR }}\AppPackages